# Generated by Django 4.1 on 2024-03-20 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_tag_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Manufacturer",
        ),
    ]
