# Generated by Django 4.1 on 2024-03-24 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="published_date",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
